name: Telegram Alert Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Secure Alert Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PENNY_STOCK_CHANNEL_ID: ${{ secrets.PENNY_STOCK_CHANNEL_ID }}
          STOCK_CHANNEL_ID: ${{ secrets.STOCK_CHANNEL_ID }}
          CRYPTO_CHANNEL_ID: ${{ secrets.CRYPTO_CHANNEL_ID }}
          WATCHLIST_CHANNEL_ID: ${{ secrets.WATCHLIST_CHANNEL_ID }}
          VALIDATION_CHANNEL_ID: ${{ secrets.VALIDATION_CHANNEL_ID }}
          WRAPUP_CHANNEL_ID: ${{ secrets.WRAPUP_CHANNEL_ID }}
          LUNARCRUSH_API_KEY: ${{ secrets.LUNARCRUSH_API_KEY }}
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
          COINMARKETCAL_API_KEY: ${{ secrets.COINMARKETCAL_API_KEY }}
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
          PEAK_START_TIME: ${{ secrets.PEAK_START_TIME }}
          PEAK_END_TIME: ${{ secrets.PEAK_END_TIME }}
          SCAN_INTERVAL_PENNY: ${{ secrets.SCAN_INTERVAL_PENNY }}
          SCAN_INTERVAL_STOCK: ${{ secrets.SCAN_INTERVAL_STOCK }}
          SCAN_INTERVAL_CRYPTO: ${{ secrets.SCAN_INTERVAL_CRYPTO }}
          ALERT_INTERVAL_PENNY_PEAK: ${{ secrets.ALERT_INTERVAL_PENNY_PEAK }}
          ALERT_INTERVAL_PENNY_OFF: ${{ secrets.ALERT_INTERVAL_PENNY_OFF }}
          ALERT_INTERVAL_CRYPTO: ${{ secrets.ALERT_INTERVAL_CRYPTO }}
        run: |
          python -m secure_alert_bot.main
